# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  cabal-docspec = {
    pname = "cabal-docspec";
    version = "0.0.0.20211114";
    src = fetchurl {
      url = "https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20211114/cabal-docspec-0.0.0.20211114.xz";
      sha256 = "12lgpv4g5lcv5b37crimbmd95n9w8fx45xf3dgncg7lckq6p0972";
    };
  };
  hellsmack = {
    pname = "hellsmack";
    version = "0.1.2.5";
    src = fetchurl {
      url = "https://github.com/amesgen/hellsmack/releases/download/v0.1.2.5/hellsmack-Linux.zip";
      sha256 = "066a5fr69f48j99kvvgxwjj95sdjgy1y65ix693a3b9bqjsdhb70";
    };
  };
  ormolu = {
    pname = "ormolu";
    version = "0.4.0.0";
    src = fetchurl {
      url = "https://github.com/tweag/ormolu/releases/download/0.4.0.0/ormolu-Linux.zip";
      sha256 = "0b3qp1lbsb2idzn7fq9lwqa7i22d58ligsxl4bn14s5hg052dms5";
    };
  };
}
